#set working direction - CHANGE THIS FOR YOUR LOCATIONS!!
setwd("E:/Dropbox/Kaggle/HIV/Adam/")

#Read in test data
test <- read.csv("adam_script_test_no_response_column_new_columns.csv", stringsAsFactors=FALSE)

#Read in training data
train <- read.csv("adam_script_train_new_columns.csv", stringsAsFactors=FALSE)

#convert Response column to factor
train['Resp'] <- lapply(train['Resp'],as.character)
train['Resp'] <- lapply(train['Resp'],as.factor)


#all the new frequency columns were imported as chr, need to conver them all to numeric
test['PR.A'] <- lapply(test['PR.A'],as.numeric)
test['PR.B'] <- lapply(test['PR.B'],as.numeric)
test['PR.C'] <- lapply(test['PR.C'],as.numeric)
test['PR.D'] <- lapply(test['PR.D'],as.numeric)
test['PR.E'] <- lapply(test['PR.E'],as.numeric)
test['PR.F'] <- lapply(test['PR.F'],as.numeric)
test['PR.G'] <- lapply(test['PR.G'],as.numeric)
test['PR.H'] <- lapply(test['PR.H'],as.numeric)
test['PR.I'] <- lapply(test['PR.I'],as.numeric)
test['PR.K'] <- lapply(test['PR.K'],as.numeric)
test['PR.L'] <- lapply(test['PR.L'],as.numeric)
test['PR.M'] <- lapply(test['PR.M'],as.numeric)
test['PR.N'] <- lapply(test['PR.N'],as.numeric)
test['PR.P'] <- lapply(test['PR.P'],as.numeric)
test['PR.Q'] <- lapply(test['PR.Q'],as.numeric)
test['PR.R'] <- lapply(test['PR.R'],as.numeric)
test['PR.S'] <- lapply(test['PR.S'],as.numeric)
test['PR.T'] <- lapply(test['PR.T'],as.numeric)
test['PR.V'] <- lapply(test['PR.V'],as.numeric)
test['PR.W'] <- lapply(test['PR.W'],as.numeric)
test['PR.X'] <- lapply(test['PR.X'],as.numeric)
test['PR.Y'] <- lapply(test['PR.Y'],as.numeric)
test['PR.Z'] <- lapply(test['PR.Z'],as.numeric)
test['RT.A'] <- lapply(test['RT.A'],as.numeric)
test['RT.B'] <- lapply(test['RT.B'],as.numeric)
test['RT.C'] <- lapply(test['RT.C'],as.numeric)
test['RT.D'] <- lapply(test['RT.D'],as.numeric)
test['RT.E'] <- lapply(test['RT.E'],as.numeric)
test['RT.F'] <- lapply(test['RT.F'],as.numeric)
test['RT.G'] <- lapply(test['RT.G'],as.numeric)
test['RT.H'] <- lapply(test['RT.H'],as.numeric)
test['RT.I'] <- lapply(test['RT.I'],as.numeric)
test['RT.K'] <- lapply(test['RT.K'],as.numeric)
test['RT.L'] <- lapply(test['RT.L'],as.numeric)
test['RT.M'] <- lapply(test['RT.M'],as.numeric)
test['RT.N'] <- lapply(test['RT.N'],as.numeric)
test['RT.P'] <- lapply(test['RT.P'],as.numeric)
test['RT.Q'] <- lapply(test['RT.Q'],as.numeric)
test['RT.R'] <- lapply(test['RT.R'],as.numeric)
test['RT.S'] <- lapply(test['RT.S'],as.numeric)
test['RT.T'] <- lapply(test['RT.T'],as.numeric)
test['RT.V'] <- lapply(test['RT.V'],as.numeric)
test['RT.W'] <- lapply(test['RT.W'],as.numeric)
test['RT.X'] <- lapply(test['RT.X'],as.numeric)
test['RT.Y'] <- lapply(test['RT.Y'],as.numeric)
test['RT.Z'] <- lapply(test['RT.Z'],as.numeric)

#do it again for training data
train['PR.A'] <- lapply(train['PR.A'],as.numeric)
train['PR.B'] <- lapply(train['PR.B'],as.numeric)
train['PR.C'] <- lapply(train['PR.C'],as.numeric)
train['PR.D'] <- lapply(train['PR.D'],as.numeric)
train['PR.E'] <- lapply(train['PR.E'],as.numeric)
train['PR.F'] <- lapply(train['PR.F'],as.numeric)
train['PR.G'] <- lapply(train['PR.G'],as.numeric)
train['PR.H'] <- lapply(train['PR.H'],as.numeric)
train['PR.I'] <- lapply(train['PR.I'],as.numeric)
train['PR.K'] <- lapply(train['PR.K'],as.numeric)
train['PR.L'] <- lapply(train['PR.L'],as.numeric)
train['PR.M'] <- lapply(train['PR.M'],as.numeric)
train['PR.N'] <- lapply(train['PR.N'],as.numeric)
train['PR.P'] <- lapply(train['PR.P'],as.numeric)
train['PR.Q'] <- lapply(train['PR.Q'],as.numeric)
train['PR.R'] <- lapply(train['PR.R'],as.numeric)
train['PR.S'] <- lapply(train['PR.S'],as.numeric)
train['PR.T'] <- lapply(train['PR.T'],as.numeric)
train['PR.V'] <- lapply(train['PR.V'],as.numeric)
train['PR.W'] <- lapply(train['PR.W'],as.numeric)
train['PR.X'] <- lapply(train['PR.X'],as.numeric)
train['PR.Y'] <- lapply(train['PR.Y'],as.numeric)
train['PR.Z'] <- lapply(train['PR.Z'],as.numeric)
train['RT.A'] <- lapply(train['RT.A'],as.numeric)
train['RT.B'] <- lapply(train['RT.B'],as.numeric)
train['RT.C'] <- lapply(train['RT.C'],as.numeric)
train['RT.D'] <- lapply(train['RT.D'],as.numeric)
train['RT.E'] <- lapply(train['RT.E'],as.numeric)
train['RT.F'] <- lapply(train['RT.F'],as.numeric)
train['RT.G'] <- lapply(train['RT.G'],as.numeric)
train['RT.H'] <- lapply(train['RT.H'],as.numeric)
train['RT.I'] <- lapply(train['RT.I'],as.numeric)
train['RT.K'] <- lapply(train['RT.K'],as.numeric)
train['RT.L'] <- lapply(train['RT.L'],as.numeric)
train['RT.M'] <- lapply(train['RT.M'],as.numeric)
train['RT.N'] <- lapply(train['RT.N'],as.numeric)
train['RT.P'] <- lapply(train['RT.P'],as.numeric)
train['RT.Q'] <- lapply(train['RT.Q'],as.numeric)
train['RT.R'] <- lapply(train['RT.R'],as.numeric)
train['RT.S'] <- lapply(train['RT.S'],as.numeric)
train['RT.T'] <- lapply(train['RT.T'],as.numeric)
train['RT.V'] <- lapply(train['RT.V'],as.numeric)
train['RT.W'] <- lapply(train['RT.W'],as.numeric)
train['RT.X'] <- lapply(train['RT.X'],as.numeric)
train['RT.Y'] <- lapply(train['RT.Y'],as.numeric)
train['RT.Z'] <- lapply(train['RT.Z'],as.numeric)
